site_name: DOTS Training
repo_url: https://github.com/WaynGames/DOTS-Training
nav:
  - "Part 1: Health Regeneration": index.md

extra:
  homepage: https://www.youtube.com/@WAYNGames
  alternate:
    - name: English
      link: /DOTS-Training/en/
      lang: en
    - name: French
      link: /DOTS-Training/fr/
      lang: fr


theme:
  name: material
  logo: https://avatars.githubusercontent.com/u/47318939
  palette:   
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
plugins:
  - search
  - i18n:
      docs_structure: folder
      default_language: en
      languages:
        - locale: en
          default: true
          name: English
        - locale: fr
          name: Français
          nav_translations:
            Home: Accueil
            Getting Started: Démarrage Rapide
            Plugins Compatibility: Compatibilité des plugins