site_name: DOTS Training
logo: https://avatars.githubusercontent.com/u/47318939
repo_url: https://github.com/WaynGames/DOTS-Training
nav:
  - "Part 1: Health Regeneration": '.././p1.md'
extra:
  alternate:
    - name: English
      link: DOTS-Training/en/
      lang: en
    - name: French
      link: DOTS-Training/fr/
      lang: fr
theme:
  name: material
  language: en 

  palette:   
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black  
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
  