site_name: DOTS Training
repo_url: https://github.com/WaynGames/DOTS-Training
nav:
  - "Part 1: Health Regeneration": index.md

theme:
  name: material
  logo: https://avatars.githubusercontent.com/u/47318939
  feature:
    language-selector: true
  extra:
    alternate:
      - name: English
        link: /en/
        lang: en
      - name: Français
        link: /fr/
        lang: fr
  palette:   
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
plugins:
  - search
  - i18n:
      docs_structure: folder
      default_language: en
      languages:
        en:
          name: English
          build: true
          nav_translations:
            "Part 1: Health Regeneration": "Part 1: Health Regeneration"
        fr:
          name: Français
          build: true
          nav_translations:
            "Part 1: Health Regeneration": "Partie 1 : Régénération de la santé"