site_name: DOTS Training
logo: https://avatars.githubusercontent.com/u/47318939?v=4
nav:
  - "Part 1: Health Regeneration": index.md
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences